### ISSUE TITLE
チケットの値段の表すテーブルを追加してほしい

### ISSUE THREAD

**Issue by ruteru64** [ruteru64/a#1]
https://github.com/ruteru64/a/blob/6f3bd5e0613039086d403a4c8c60d30c8171f284/dbERfig.drawio.svg?short_path=5ac4e4d#L1

**Comment by otazero** [comment]
ありがとうございます！
ただいま修正いたしました
「チケット-料金区分」「座席情報-座席区分」に関係性を持たせて良かったのか不安です...
